/**
 * Типы событий системы
 */
const EventType = {
  // Heartbeat события
  HEARTBEAT_PONG: 'HEARTBEAT_PONG',
  HEARTBEAT_FAIL: 'HEARTBEAT_FAIL',
  HEARTBEAT_TIMEOUT: 'HEARTBEAT_TIMEOUT',

  // WebSocket события
  WS_CONNECTED: 'WS_CONNECTED',
  WS_DISCONNECTED: 'WS_DISCONNECTED',
  WS_RECONNECTING: 'WS_RECONNECTING',
  WS_ERROR: 'WS_ERROR',

  // Market Data события
  ORDERBOOK_UPDATE: 'ORDERBOOK_UPDATE',
  TRADES_UPDATE: 'TRADES_UPDATE',
  BALANCE_UPDATE: 'BALANCE_UPDATE',
  POSITION_UPDATE: 'POSITION_UPDATE',

  // System события
  SYSTEM_START: 'SYSTEM_START',
  SYSTEM_STOP: 'SYSTEM_STOP',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
};

module.exports = { EventType };
